"""add_gemini_vector_768

Revision ID: a1c8e1f4d256
Revises: 37343e7cd9c0
Create Date: 2026-09-16 19:03:38.872603

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c8e1f4d256"
down_revision: str | Sequence[str] | None = "37343e7cd9c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("incidents", sa.Column("ai_rca_summary", sa.Text(), nullable=True))
    op.add_column(
        "incidents",
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("incidents", "embedding")
    op.drop_column("incidents", "ai_rca_summary")
    # ### end Alembic commands ###
